#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

autoload bashcompinit
bashcompinit

if [[ -f /etc/bash_completion.d/vzctl.sh ]]; then
  source /etc/bash_completion.d/vzctl.sh
fi

if [[ -f /etc/bash_completion.d/prlctl.sh ]]; then
  source /etc/bash_completion.d/prlctl.sh
fi

if [[ -f $HOME/.zsh-override ]]; then
   source $HOME/.zsh-override
fi
